version: '3.4'

services:
  platankaapi:
    env_file:
      - .env
    container_name: platankaapi
    image: platankaapi:latest
    build:
      context: .
      dockerfile: PlatankaAPI/Dockerfile
    ports:
      - 8000:80
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db-data/mongo/:/data/db
    ports:
      - 27017:27017

  platankaweb:
    container_name: platankaweb
    image: platankaweb:latest
    build: ./platankaweb
    ports:
      - 3000:3000
    restart: always
    networks:
      - platanka
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   platanka:
#     external: true